#!/bin/bash

user_interrupt(){
    echo -e "\n\nKeyboard Interrupt detected."
    echo -e "Cleaning Up and terminating..."
    exit
}

trap user_interrupt SIGINT
trap user_interrupt SIGTSTP

while getopts "h?d:f:" opt; do
    case "$opt" in
	h|\?)
	    echo "Usage: $0 -f <csv file path> [-d 'developer name']..."
	    exit 0
	    ;;
	f) FNAME=$OPTARG
	   ;;
	d) DEVELOPER=$OPTARG
	   ;;
    esac
done

if [ -z $FNAME ]; then
    echo "Usage: $0 -f <csv file path> [-d 'developer name']..."
    exit 1
fi

if [ ! -f $FNAME ]; then
    echo "ERROR: You need to specify a filename!"
    echo "Example: ./agent -f singapore-property-data.csv -d 'FCL Peak Pte Ltd'"
    exit 1
fi

if [[ -z $DEVELOPER ]]; then
    # sets a test name from last line of input file
    DEVELOPER=$(tail -n 1 $FNAME | awk -F ',' '{print $5}')
    echo -e "Since you didn't set a developer, here's a sample."
fi

start_pan(){

    echo "$DEVELOPER"
    echo "===================="
    # Or set manually, example: FCL Peak Pte Ltd

    echo "Street names"
    grep "$DEVELOPER" $FNAME | awk -F ',' '{print "\t"$4}' \
        | sort | uniq
    echo "--------------------"
    echo "Project names"
    grep "$DEVELOPER" $FNAME | awk -F ',' '{print "\t"$3}' \
        | sort | uniq
    echo "--------------------"
    echo "Active Years: "
    grep "$DEVELOPER" $FNAME | awk -F ',' '{print "\t"$1}' \
        | sort | uniq | sed s/"\t"/""/g | tr '\n' ' ' #sed ':a;N;$!ba;s/\n/ /g'
    echo
}

start_pan
# property_analyzer -f singapore-property-data.csv 
