primes = [ 's', 't', 'v', 'x', 'rr', 'rt', 'rx', 'rz', 'st', 'sz',
    'tr', 'tx', 'ur', 'ut', 'ux', 'vt', 'vz', 'wr', 'wx', 'xr', 'xt',
    'xz', 'yt', 'yz', 'zx', 'rqr', 'rqt', 'rqx', 'rqz', 'rrt', 'rsx',
    'rtr', 'rtx', 'rtz', 'ruz', 'rvr', 'rvx', 'rwt', 'rwx', 'rxt', 'rxz',
    'ryr', 'rzr', 'rzt', 'rzx', 'rzz', 'srr', 'sst', 'ssx', 'ssz', 'stt',
    'stz', 'sur', 'svr', 'svx', 'swt', 'swz', 'sxr', 'sxx', 'syr', 'syt',
    'szt', 'tqx', 'trr', 'trt', 'trx', 'ttr', 'ttx', 'tux', 'tuz', 'tvt',
    'tvz', 'twx', 'txt', 'txz', 'tyt', 'tyz', 'tzx', 'uqr', 'uqz', 'urz',
    'usr', 'utr', 'utt', 'utz', 'uut', 'uuz', 'uvx', 'uwr', 'uwt', 'uwx',
    'uxz', 'uyx', 'uzr', 'uzz', 'vqt', 'vqz', 'vsr', 'vst', 'vur', 'vux',
    'vvx', 'vwt', 'vwz', 'vxr', 'vxx', 'vyx', 'vzt', 'vzz', 'wqr', 'wqx',
    'wrt', 'wrx', 'wrz', 'wtr', 'wur', 'wut', 'wux', 'wvt', 'wvz', 'wwr',
    'wxt', 'wxx', 'wyt', 'wzr', 'xqr', 'xqz', 'xrz', 'xsx', 'xtt', 'xtz',
    'xut', 'xvr', 'xvx', 'xwr', 'xwz', 'xxt', 'xyx', 'xzx', 'yqz', 'yrr',
    'ysr', 'yst', 'ysx', 'ysz', 'ytz', 'yvt', 'yvx', 'yvz', 'ywt', 'yxx',
    'yyr', 'yyt', 'yyx', 'zqx', 'zrr', 'zrz', 'zsz', 'ztx', 'zur', 'zux',
    'zvt', 'zwx', 'zxr', 'zxx', 'zyt', 'zzr', 'zzx', 'rqqz', 'rqrt',
    'rqrz', 'rqsr', 'rqtr', 'rqtt', 'rqtz', 'rquz', 'rqvr', 'rqwr',
    'rqwt', 'rqwz', 'rqyx', 'rqzr', 'rqzt', 'rqzx', 'rrqt', 'rrqz',
    'rrrx', 'rrst', 'rrsz', 'rrvr', 'rrvt', 'rrwt', 'rrxr', 'rryr',
    'rryx', 'rrzt', 'rsqr', 'rsrt', 'rsrx', 'rsst', 'rssz', 'rstr',
    'rstx', 'rsuz', 'rsvz', 'rsxx', 'rsxz', 'rsyt', 'rsyz', 'rszr',
    'rszx', 'rtqr', 'rtqt', 'rtqx', 'rtrz', 'rtsr', 'rtsx', 'rtwr',
    'rtwx', 'rtxt', 'rtyr', 'rtzz', 'ruqz', 'rust', 'rusx', 'rusz',
    'rutt', 'rutz', 'ruux', 'ruvr', 'ruvt', 'ruvz', 'ruxr', 'ruyr',
    'ruyt', 'ruyx', 'ruyz', 'ruzt', 'ruzz', 'rvrr', 'rvst', 'rvtr',
    'rvut', 'rvuz', 'rvvt', 'rvvz', 'rvwx', 'rvxr', 'rvxz', 'rvyt',
    'rvzx', 'rwqr', 'rwqx', 'rwqz', 'rwrt', 'rwrz', 'rwsr', 'rwsx',
    'rwtx', 'rwvx', 'rwwt', 'rwwx', 'rwwz', 'rwzt', 'rwzx', 'rwzz',
    'rxqz', 'rxsr', 'rxst', 'rxtt', 'rxur', 'rxux', 'rxvt', 'rxvz',
    'rxxx', 'rxyt', 'rxyx', 'rxyz', 'ryqr', 'ryrr', 'ryst', 'rytr',
    'ryux', 'rywr', 'rywx', 'ryxr', 'ryxt', 'ryxx', 'ryxz', 'ryyz',
    'rzqr', 'rzqx', 'rzrt', 'rztr', 'rztt', 'rzuz', 'rzvr', 'rzxt',
    'rzxz', 'rzyx', 'rzzt', 'rzzx', 'rzzz', 'sqqt', 'sqrr', 'sqrx',
    'sqsx', 'sqsz', 'sqtz', 'sqvt', 'sqwt', 'sqwz', 'sqyr', 'sqyt',
    'sqyx', 'sqyz', 'sqzz', 'srrr', 'srrt', 'srsz', 'srtr', 'srtx',
    'srur', 'srut', 'srvt', 'srwr', 'srxz', 'ssqt', 'ssqx', 'ssrt',
    'sssr', 'sstx', 'sstz', 'ssut', 'ssvr', 'sswx', 'sswz', 'ssxt',
    'ssyr', 'ssyx', 'sszt', 'sszx', 'stqz', 'strr', 'sttt', 'sttz',
    'stur', 'stux', 'stvr', 'stvx', 'stxr', 'stxx', 'styr', 'styt',
    'styz', 'stzt', 'stzz', 'surr', 'surx', 'sust', 'sutx', 'suur',
    'suux', 'suvz', 'suwx', 'suxt', 'suxx', 'svqt', 'svsr', 'svtr',
    'svtz', 'svut', 'svuz', 'svvr', 'svvx', 'svxz', 'svzr', 'svzt',
    'swqz', 'swrx', 'swsr', 'swtt', 'swux', 'swvx', 'swvz', 'swwt',
    'swxr', 'swxx', 'swyt', 'swyx', 'swyz', 'swzt', 'swzz', 'sxqx',
    'sxrr', 'sxrt', 'sxrz', 'sxsz', 'sxtr', 'sxur', 'sxuz', 'sxvt',
    'sxwx', 'sxxx', 'sxyz', 'sxzr', 'sxzx', 'syqr', 'syqt', 'syrz',
    'sytt', 'sytx', 'syut', 'syvr', 'syvx', 'sywr', 'syxz', 'syyx',
    'syzx', 'szqt', 'szqz', 'szrx', 'szsx', 'sztz', 'szvt', 'szvx',
    'szwt', 'szwz', 'szxr', 'szzz', 'tqqr', 'tqrr', 'tqrz', 'tqst',
    'tqtx', 'tqur', 'tquz', 'tqwr', 'tqwx', 'tqxz', 'tqyt', 'tqyz',
    'trqz', 'trrz', 'trsr', 'trtx', 'trwt', 'trwx', 'trwz', 'tryr',
    'tryx', 'trzr', 'tsqt', 'tsqz', 'tsrx', 'tssr', 'tssz', 'tsvr',
    'tsvt', 'tsvx', 'tsvz', 'tsxr', 'tszz', 'ttqr', 'ttqx', 'ttrt',
    'ttrz', 'ttst', 'ttsz', 'tttr', 'ttut', 'ttux', 'ttvz', 'ttwr',
    'ttxr', 'ttxt', 'ttyz', 'ttzr', 'tuqx', 'turt', 'tutt', 'tuuz',
    'tuvx', 'tuwr', 'tuwt', 'tuwx', 'tuwz', 'tuzr', 'tuzz', 'tvrr',
    'tvrx', 'tvsx', 'tvsz', 'tvtt', 'tvtz', 'tvur', 'tvux', 'tvvx',
    'tvvz', 'tvxr', 'tvyr', 'tvyt', 'tvzt', 'twqx', 'twrt', 'twrx',
    'twst', 'twtr', 'twtx', 'twut', 'twvz', 'twxr', 'twxt', 'twxx',
    'twzr', 'twzx', 'txqr', 'txqz', 'txrz', 'txsx', 'txtt', 'txtz',
    'txwr', 'txwx', 'txwz', 'txxz', 'txzt', 'txzx', 'tyqt', 'tysr',
    'tyst', 'tytt', 'tyux', 'tyvr', 'tyvt', 'tywt', 'tyxx', 'tyyr',
    'tyyz', 'tzqx', 'tzrr', 'tzrx', 'tzrz', 'tzst', 'tzsz', 'tztr',
    'tzut', 'tzux', 'tzwx', 'tzyz', 'uqqr', 'uqqt', 'uqqx', 'uqrt',
    'uqrz', 'uqsr', 'uqsx', 'uquz', 'uqvr', 'uqvx', 'uqxt', 'uqxz',
    'uqzr', 'uqzt', 'uqzz', 'urrr', 'ursx', 'ursz', 'urtt', 'urtz',
    'urvt', 'urvx', 'urvz', 'urxx', 'usqr', 'usrr', 'usrx', 'usrz',
    'ussz', 'ustr', 'usur', 'usut', 'usvt', 'usvz', 'uswr', 'usxr',
    'usxt', 'usyt', 'usyz', 'uszx', 'utsx', 'uttx', 'uttz', 'utuz',
    'utvx', 'utwt', 'utxt', 'utzr', 'utzx', 'uuqz', 'uusr', 'uust',
    'uuur', 'uuux', 'uuvr', 'uuvx', 'uuwt', 'uuyr', 'uuyt', 'uuzt',
    'uvqx', 'uvrt', 'uvrx', 'uvrz', 'uvst', 'uvux', 'uvuz', 'uvwr',
    'uvwx', 'uvyt', 'uvzr', 'uvzx', 'uwqt', 'uwsr', 'uwtx', 'uwtz',
    'uwut', 'uwuz', 'uwvr', 'uwvx', 'uwwt', 'uwxt', 'uwxz', 'uwzr',
    'uxqt', 'uxsr', 'uxst', 'uxsz', 'uxtt', 'uxvr', 'uxvz', 'uxyt',
    'uxyx', 'uxyz', 'uxzt', 'uxzz', 'uyqr', 'uyrt', 'uyrx', 'uytr',
    'uywr', 'uyxr', 'uyxx', 'uyyz', 'uzqt', 'uzqz', 'uzrz', 'uztr',
    'uztt', 'uztx', 'uzut', 'uzvr', 'uzvx', 'uzwx', 'uzwz', 'uzxt',
    'uzyx', 'uzzt', 'uzzz', 'vqqt', 'vqqz', 'vqrr', 'vqsr', 'vqst',
    'vqtz', 'vqvr', 'vqvz', 'vqxx', 'vqyr', 'vqyx', 'vqzz', 'vrqr',
    'vrqx', 'vrrt', 'vrrz', 'vrux', 'vrvt', 'vrwx', 'vrxr', 'vrxz',
    'vryz', 'vrzx', 'vsqz', 'vssx', 'vstr', 'vstt', 'vstx', 'vswr',
    'vsxt', 'vsxz', 'vsyr', 'vszx', 'vtqt', 'vtqz', 'vtst', 'vttt',
    'vtux', 'vtvr', 'vtyr', 'vtyx', 'vtzt', 'vtzz', 'vuqx', 'vurt',
    'vurx', 'vurz', 'vutr', 'vutx', 'vuur', 'vuut', 'vuuz', 'vuxr',
    'vuxx', 'vuxz', 'vuyt', 'vvqr', 'vvqt', 'vvqx', 'vvrz', 'vvsr',
    'vvsx', 'vvtr', 'vvvx', 'vvwt', 'vvwz', 'vvxt', 'vvyr', 'vvzr',
    'vwst', 'vwtz', 'vwur', 'vwux', 'vwvr', 'vwvt', 'vwvx', 'vwvz',
    'vwwz', 'vwyt', 'vwyz', 'vwzt', 'vxqr', 'vxrr', 'vxrx', 'vxtx',
    'vxur', 'vxut', 'vxuz', 'vxxz', 'vxyt', 'vxzr', 'vyqr', 'vyqx',
    'vyrt', 'vysr', 'vysx', 'vytz', 'vyut', 'vyuz', 'vyvr', 'vyvx',
    'vywr', 'vywx', 'vywz', 'vyxz', 'vyyr', 'vyzx', 'vzqt', 'vzst',
    'vzsx', 'vztz', 'vzvt', 'vzyr', 'vzyx', 'wqqx', 'wqrr', 'wqsz',
    'wqtx', 'wqut', 'wqux', 'wqvt', 'wqwx', 'wqxt', 'wqxz', 'wqyz',
    'wqzr', 'wrqr', 'wrrt', 'wrsr', 'wrtr', 'wrtt', 'wrut', 'wrvr',
    'wrwt', 'wrxt', 'wrzx', 'wrzz', 'wsqt', 'wsrr', 'wsrx', 'wssr',
    'wssz', 'wsux', 'wsvx', 'wswt', 'wswz', 'wsxr', 'wsxx', 'wsyx',
    'wszz', 'wtqr', 'wtrr', 'wtrx', 'wtst', 'wtsz', 'wttx', 'wtut',
    'wtvt', 'wtvz', 'wtwr', 'wtwx', 'wtxt', 'wtxz', 'wtyz', 'wtzx',
    'wusr', 'wusx', 'wuuz', 'wuvr', 'wuwz', 'wuxt', 'wuyr', 'wuzr',
    'wvsr', 'wvsz', 'wvux', 'wvvr', 'wvvt', 'wvwt', 'wvwz', 'wvxr',
    'wvxx', 'wvyr', 'wvzz', 'wwqx', 'wwrz', 'wwtx', 'wwvt', 'wwvz',
    'wwwr', 'wwxt', 'wwxz', 'wwyz', 'wwzr', 'wxqr', 'wxqt', 'wxqz',
    'wxrz', 'wxtt', 'wxtx', 'wxwr', 'wxwt', 'wxxz', 'wxyr', 'wxzr',
    'wxzt', 'wyqt', 'wyst', 'wysx', 'wysz', 'wytt', 'wyur', 'wyvx',
    'wywt', 'wywz', 'wyxr', 'wyyt', 'wyzz', 'wzqx', 'wzrr', 'wzrx',
    'wzux', 'wzuz', 'wzvz', 'wzwr', 'wzwx', 'wzxr', 'wzxx', 'wzyt',
    'wzzr', 'wzzx', 'xqqr', 'xqrt', 'xqrz', 'xqsx', 'xqtz', 'xqut',
    'xqvx', 'xqwz', 'xqxz', 'xrqt', 'xrqz', 'xrsr', 'xrsx', 'xrsz',
    'xrvr', 'xrvz', 'xrxx', 'xryx', 'xrzt', 'xsqx', 'xsrr', 'xsrt',
    'xsrz', 'xssz', 'xstx', 'xsut', 'xsux', 'xsvt', 'xsyt', 'xszx',
    'xtqx', 'xtqz', 'xtsr', 'xttr', 'xttt', 'xtuz', 'xtvr', 'xtwz',
    'xtzt', 'xurr', 'xurx', 'xutt', 'xuvr', 'xuvx', 'xuvz', 'xuxx',
    'xuyr', 'xuyx', 'xuyz', 'xuzz', 'xvqx', 'xvrx', 'xvst', 'xvsz',
    'xvtx', 'xvur', 'xvux', 'xvuz', 'xvvz', 'xvwr', 'xvxt', 'xvxx',
    'xvyt', 'xvyz', 'xvzr', 'xwqt', 'xwqx', 'xwsr', 'xwtz', 'xwut',
    'xwuz', 'xwwz', 'xwxt', 'xwyr', 'xwyx', 'xwzr', 'xwzz', 'xxqt',
    'xxrx', 'xxst', 'xxsx', 'xxur', 'xxvt', 'xxvx', 'xxvz', 'xxyz',
    'xxzt', 'xyrx', 'xyst', 'xysz', 'xyur', 'xyvt', 'xywx', 'xyxt',
    'xyxx', 'xyxz', 'xyyt', 'xzqr', 'xzqx', 'xzrz', 'xzsx', 'xztt',
    'xztx', 'xzuz', 'xzvr', 'xzwt', 'xzzt', 'yqqz', 'yqrr', 'yqrx',
    'yqtz', 'yqvt', 'yqvz', 'yqwz', 'yqyr', 'yqyx', 'yqyz', 'yqzt',
    'yrqr', 'yrrr', 'yrrx', 'yrst', 'yrux', 'yrwr', 'yrwx', 'yrxr',
    'yrxz', 'yrzr', 'ysqz', 'ysrz', 'yssr', 'ystr', 'ystt', 'ystx',
    'ysut', 'yswt', 'yswz', 'ysxt', 'ysyx', 'yszr', 'yszt', 'yszx',
    'ytrr', 'ytrx', 'ytsz', 'ytvt', 'ytwt', 'ytwz', 'ytxx', 'ytyx',
    'ytyz', 'yurz', 'yust', 'yusz', 'yutr', 'yuut', 'yuux', 'yuwr',
    'yuwx', 'yvqr', 'yvrt', 'yvsr', 'yvsx', 'yvtx', 'yvtz', 'yvut',
    'yvwt', 'yvxt', 'yvyr', 'yvzx', 'yvzz', 'ywqz', 'ywst', 'ywsx',
    'ywsz', 'ywur', 'ywux', 'ywwt', 'ywwz', 'ywxx', 'ywyr', 'ywyz',
    'ywzt', 'ywzz', 'yxqx', 'yxrt', 'yxrz', 'yxtr', 'yxtx', 'yxur',
    'yxux', 'yxvt', 'yxwr', 'yxxz', 'yxyt', 'yyqt', 'yyqx', 'yyrz',
    'yysr', 'yytr', 'yytx', 'yytz', 'yyuz', 'yywr', 'yywt', 'yywx',
    'yyyx', 'yyzt', 'yzst', 'yzsz', 'yztt', 'yzur', 'yzvr', 'yzwt',
    'yzwz', 'yzxr', 'yzzz', 'zqqr', 'zqqx', 'zqrr', 'zqrt', 'zqsz',
    'zqur', 'zqut', 'zquz', 'zqvz', 'zqwx', 'zqzr', 'zrqt', 'zrqz',
    'zrsx', 'zrtt', 'zrtx', 'zrvr', 'zrvx', 'zrwr', 'zrxt', 'zryr',
    'zryx', 'zrzz', 'zsqt', 'zsqz', 'zssr', 'zssx', 'zstz', 'zsur',
    'zsvx', 'zsxx', 'zsyr', 'zsyt', 'zszt', 'ztrr', 'ztrz', 'ztst',
    'zttx', 'ztur', 'ztut', 'ztuz', 'ztxr', 'ztxx', 'ztzr', 'ztzx',
    'zuqt', 'zurt', 'zurz', 'zusr', 'zutr', 'zutt', 'zutx', 'zutz',
    'zuwr', 'zuwt', 'zuwx', 'zuxt', 'zuxz', 'zuzr', 'zuzx', 'zvrr',
    'zvsr', 'zvtt', 'zvtz', 'zvux', 'zvvr', 'zvyx', 'zwqr', 'zwrt',
    'zwrz', 'zwst', 'zwsz', 'zwtr', 'zwut', 'zwuz', 'zwwr', 'zwxx',
    'zwxz', 'zwyz', 'zwzx', 'zxrz', 'zxsr', 'zxtt', 'zxtz', 'zxut',
    'zxuz', 'zxwx', 'zxwz', 'zxyr', 'zxyx', 'zxzr', 'zyqt', 'zyrr',
    'zyrx', 'zysz', 'zytt', 'zytz', 'zyvr', 'zyvx', 'zyvz', 'zyxr',
    'zyyt', 'zyyx', 'zzqr', 'zzqx', 'zzst', 'zzsz', 'zztr', 'zzur',
    'zzuz', 'zzwx', 'zzxt' ]
     
def checkio(number):
    s = ''
    for c in str(number):
        s = s + chr(ord(c) + ord('A'))
    return (s in primes)

print checkio(int(raw_input()))
